[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "armv5te-none-eabi"

[target.armv5te-none-eabi]
rustflags = [
    "-C", "link-arg=-Tarm9bios.ld",
    "-C", "link-arg=--nmagic",
    "-C", "relocation-model=static",
    "-C", "opt-level=z",
    "-C", "lto=fat",
    "-C", "codegen-units=1",
    "-C", "panic=abort",
]